{% set name = "hls4ml" %}
{% set version = "0.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hls4ml-{{ version }}.tar.gz
  sha256: bc003730ef01af86ab3b1c51d5c504140e2bf4545384c8973cadfb28630c0c18

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - h5py
    - numpy
    - onnx >=1.4.0
    - python >=3.6
    - pyyaml
    - six

test:
  imports:
    - hls4ml
    - hls4ml.converters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hls-fpga-machine-learning/hls4ml
  summary: Machine learning in FPGAs using HLS
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jmitrevs
    - ngpaladi
    - vloncar
    - Duchstf
    - jmduarte
