{% set name = "hls4ml" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hls4ml-{{ version }}.tar.gz
  sha256: af62da04ee8bee44c512abeee91222a963e575f814330c815aaaff2ed5e75d9a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - wheel
  run:
    - h5py
    - numpy
    - onnx >=1.4.0
    - python >=3.6
    - pyyaml
    - six
    - tabulate

test:
  imports:
    - contrib
    - hls4ml
    - hls4ml.converters
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://fastmachinelearning.org/hls4ml
  summary: Machine learning in FPGAs using HLS
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jmitrevs
    - ngpaladi
    - vloncar
    - Duchstf
    - jmduarte
